-- 코드를 입력하세요
select
    A.PRODUCT_CODE PRODUCT_CODE,sum(A.PRICE*B.SALES_AMOUNT) SALES
from 
    PRODUCT A join OFFLINE_SALE B 
    on A.PRODUCT_ID=B.PRODUCT_ID
group by A.PRODUCT_CODE
order by SALES desc,PRODUCT_CODE